
sudo: required
services:
    - docker
before_install:
    - docker build -t jisacson/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jisacson/react-test npm test

after_success:
    - docker build -t jisacson/multi-client ./client
    - docker build -t jisacson/multi-nginx ./nginx
    - docker build -t jisacson/multi-server ./server
    - docker build -t jisacson/multi-worker ./worker
    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take image and push them to docker hub
    - docker push jisacson/multi-client
    - docker push jisacson/multi-nginx
    - docker push jisacson/multi-server
    - docker push jisacson/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-448649140700"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
